# Generated by Django 6.0.3 on 2026-03-14 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_expensecomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseLender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lenders', to='api.expense')),
            ],
        ),
    ]
