# Generated by Django 4.2.29 on 2026-03-15 17:25

import uuid
from django.db import migrations, models


def populate_invite_codes(apps, schema_editor):
    """Generate unique invite codes for existing groups that have empty codes."""
    Group = apps.get_model('api', 'Group')
    for group in Group.objects.filter(invite_code=''):
        group.invite_code = uuid.uuid4().hex[:12]
        group.save(update_fields=['invite_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_expenselender'),
    ]

    operations = [
        # Step 1: Add the field without unique constraint
        migrations.AddField(
            model_name='group',
            name='invite_code',
            field=models.CharField(blank=True, max_length=12, default=''),
        ),
        # Step 2: Populate existing rows with unique codes
        migrations.RunPython(populate_invite_codes, migrations.RunPython.noop),
        # Step 3: Now apply the unique constraint
        migrations.AlterField(
            model_name='group',
            name='invite_code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
